sudo: false

language: go
go:
  - 1.9

before_install:
  - go get -u github.com/golang/dep/cmd/dep github.com/golang/lint/golint
  - go get github.com/mitchellh/gox

script:
  - dep ensure
  - golint $(go list ./... | grep -v /vendor/)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -cover $(go list ./... | grep -v /vendor/)

before_deploy:
  - gox -os "linux darwin" -arch "386 amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/transporter/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false